import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/css/auth.css',
                'resources/js/auth.js',
                'resources/css/commission/detail.css',
                'resources/js/commission/detail.js',
                'resources/css/commission/order-detail.css',
                'resources/js/commission/order-detail.js',
                'resources/css/dashboards/artist.css',
                'resources/js/dashboards/artist.js',
                'resources/css/dashboards/profile.css',
                'resources/js/dashboards/profile.js',
                'resources/css/homepage/home.css',
                'resources/css/layouts/app.css',
                'resources/js/layouts/app.js',
                'resources/css/layouts/ordernav.css',
                'resources/js/layouts/ordernav.js',
                'resources/css/layouts/topnav.css',
                'resources/js/layouts/topnav.js',
                'resources/css/page/explore.css',
                'resources/js/page/explore.js',
                'resources/css/page/popup.css',
                'resources/js/page/popup.js',
                'resources/css/pages/cart.css',
                'resources/js/pages/cart.js',
                'resources/css/pages/chat-list.css',
                'resources/css/pages/chat-thread.css',
                'resources/js/pages/chat-thread.js',
                'resources/css/pages/notifications.css',
                'resources/js/pages/notifications.js',
                'resources/css/admin/login.css',
                'resources/js/admin/login.js',
                'resources/css/pages/verification.css',
                'resources/js/pages/verification.js',
                'resources/css/admin/admin.css',
                'resources/css/admin/login.css',
                'resources/css/admin/users.css',
                'resources/css/pages/verification/index.css',
                'resources/css/pages/verification/show.css',
                'resources/js/admin/admin-layout.js',
                'resources/js/admin/login.js',
                'resources/js/pages/verification/show.js',
                'resources/js/pages/verification/create.js',
                'resources/js/pages/verification/show.js',
                'resources/css/pages/verification/create.css',
                'resources/css/pages/verification/status.css',
                'resources/css/admin/home-setting.css',
                'resources/js/admin/home-setting.js',
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
});
